name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16, 18, 20]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Generate version file
      run: make lib/version.js
    
    - name: Run linting
      run: make lint
    
    - name: Run unit tests
      run: make unit-test
    
    - name: Build project
      run: make build/dagre.js
    
    - name: Run browser tests
      run: make browser-test
    
    - name: Build distribution
      run: make dist
      if: matrix.node-version == '20'
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      if: matrix.node-version == '20'
      with:
        directory: ./.nyc_output